//! Acceptance test for AC1 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: morsel (lib)
//! AC description: Linear (dense) layer: given a weight matrix W ([out, in]) and bias b ([out]), compute y = W * x + b for an input slice x ([in]). Output matches a hand-computed numeric reference within 1e-6.
//! Test predicate: tests/acceptance_ac1.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac1` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(
    clippy::similar_names,
    clippy::cast_precision_loss,
    clippy::cast_possible_truncation,
    clippy::cast_sign_loss,
    clippy::as_conversions,
    clippy::needless_range_loop,
    clippy::suboptimal_flops,
    clippy::excessive_precision,
    clippy::many_single_char_names,
    clippy::print_stderr,
    clippy::explicit_iter_loop,
    clippy::redundant_clone
)]
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::doc_markdown,
    clippy::float_arithmetic,
    clippy::indexing_slicing
)]

use morsel::linear::linear;

#[test]
fn acceptance_ac1() {
    // 3-input, 2-output dense layer with hand-set weights.
    // y0 = 0.5*x0 + 1.0*x1 + (-0.5)*x2 + 0.1
    // y1 = 2.0*x0 + (-1.0)*x1 + 0.25*x2 + (-0.2)
    let w: [[f32; 3]; 2] = [[0.5, 1.0, -0.5], [2.0, -1.0, 0.25]];
    let b: [f32; 2] = [0.1, -0.2];
    let x: [f32; 3] = [1.0, 2.0, 4.0];
    let mut y: [f32; 2] = [0.0; 2];

    linear(&w, &b, &x, &mut y);

    // Hand-computed references:
    // y0 = 0.5*1 + 1.0*2 + (-0.5)*4 + 0.1 = 0.5 + 2.0 - 2.0 + 0.1 = 0.6
    // y1 = 2.0*1 + (-1.0)*2 + 0.25*4 + (-0.2) = 2.0 - 2.0 + 1.0 - 0.2 = 0.8
    let expected = [0.6_f32, 0.8_f32];
    let tol = 1e-6_f32;

    for i in 0..2 {
        let diff = (y[i] - expected[i]).abs();
        assert!(
            diff < tol,
            "AC1: y[{i}] = {} expected {} diff {} > tol {}",
            y[i],
            expected[i],
            diff,
            tol
        );
    }

    // Edge case: identity-ish 1x1 layer.
    let w1: [[f32; 1]; 1] = [[3.0]];
    let b1: [f32; 1] = [-1.0];
    let x1: [f32; 1] = [2.0];
    let mut y1: [f32; 1] = [0.0];
    linear(&w1, &b1, &x1, &mut y1);
    assert!((y1[0] - 5.0).abs() < tol, "AC1 1x1: got {}", y1[0]);
}
