//! Acceptance test for AC7 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: morsel (lib)
//! AC description: Allocation-free inference: a benchmark/integration test calls a representative composed pipeline (Lstm step + Linear + Sigmoid) using only caller-provided output buffers; no Vec / Box / heap allocation occurs inside the primitives' hot path. Verified by structuring the primitive APIs to write into `&mut [f32]` outputs rather than returning Vec; the test is a compile-time guarantee plus a runtime assertion that the same output buffer is reused across 100 calls without panic.
//! Test predicate: tests/acceptance_ac7.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac7` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

#[test]
fn acceptance_ac7() {
    // edit-agent: replace this stub with a real assertion. The
    // panic keeps the test failing until you do, so the loop
    // sees a real Stage 3 signal.
    panic!("AC AC7 not yet implemented — see file header");
}
