//! Acceptance test for AC6 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: morsel (lib)
//! AC description: End-to-end worked example (XOR-LSTM in tests): hand-set weights in a test file produce a tiny LSTM that classifies a 4-symbol sequence pattern; the test runs Lstm + Linear + Softmax + Argmax through the library and asserts the predicted class is correct for at least 3 of 4 canonical inputs. This exercises composition of all primitives, not a single primitive in isolation.
//! Test predicate: tests/acceptance_ac6.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac6` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

#[test]
fn acceptance_ac6() {
    // edit-agent: replace this stub with a real assertion. The
    // panic keeps the test failing until you do, so the loop
    // sees a real Stage 3 signal.
    panic!("AC AC6 not yet implemented — see file header");
}
