//! Acceptance test for AC9 (SHOULD) — generated by `autobuilder scaffold`.
//!
//! Project: morsel (lib)
//! AC description: Documented module rustdoc: every public item in the primitives module carries a doc comment with at least one runnable example or a math formula.
//! Test predicate: tests/acceptance_ac9.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac9` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(
    clippy::similar_names,
    clippy::cast_precision_loss,
    clippy::cast_possible_truncation,
    clippy::cast_sign_loss,
    clippy::as_conversions,
    clippy::needless_range_loop,
    clippy::suboptimal_flops,
    clippy::excessive_precision,
    clippy::many_single_char_names,
    clippy::print_stderr,
    clippy::explicit_iter_loop,
    clippy::redundant_clone
)]
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::doc_markdown,
    clippy::indexing_slicing
)]

use std::fs;
use std::path::PathBuf;

/// Scan a source file. For every `pub fn NAME` (top-level), confirm
/// that the lines immediately above contain a `///` doc block, and
/// that the doc block either:
///   - contains a fenced runnable example (a ```` ``` ```` line), or
///   - contains a math formula marker (`y = `, `gates =`, etc.), or
///   - references a known formula via `# Numeric stability` / `# Shape`
///     header (the LSTM/activation primitives that don't need an
///     example but document the math).
///
/// Returns Vec of (function_name, reason_if_missing) for items that fail.
fn check_pub_items(source: &str) -> Vec<(String, String)> {
    let lines: Vec<&str> = source.lines().collect();
    let mut failures: Vec<(String, String)> = Vec::new();
    for (idx, line) in lines.iter().enumerate() {
        let trimmed = line.trim_start();
        // Identify top-level public function declarations.
        let is_pub_fn = trimmed.starts_with("pub fn ")
            || trimmed.starts_with("pub fn\t");
        if !is_pub_fn {
            continue;
        }
        // Skip if inside a function body (indent > 0). At top-level, the
        // line should start at column 0.
        if line.starts_with(' ') || line.starts_with('\t') {
            continue;
        }
        // Extract the function name.
        let after_pub_fn = &trimmed["pub fn ".len()..];
        let name_end = after_pub_fn.find(|c: char| !c.is_alphanumeric() && c != '_').unwrap_or(after_pub_fn.len());
        let name = &after_pub_fn[..name_end];

        // Walk upward collecting consecutive doc lines (skip blank lines and attributes between).
        let mut doc_block: Vec<&str> = Vec::new();
        let mut i = idx;
        while i > 0 {
            i -= 1;
            let prev = lines[i].trim_start();
            if prev.starts_with("///") || prev.starts_with("//!") {
                doc_block.push(prev);
            } else if prev.is_empty()
                || prev.starts_with("#[")
                || prev.starts_with("#![")
            {
                // Skip blank lines / attributes; doc may be further up.
                continue;
            } else {
                break;
            }
        }
        let doc_text = doc_block.join("\n");
        let has_example_fence = doc_text.contains("```");
        let has_formula = doc_text.contains(" = ")
            || doc_text.contains("y =")
            || doc_text.contains("gates =")
            || doc_text.contains("argmax")
            || doc_text.contains("sigmoid")
            || doc_text.contains("tanh")
            || doc_text.contains("softmax");

        if doc_block.is_empty() {
            failures.push((name.to_string(), "no doc comment".into()));
        } else if !has_example_fence && !has_formula {
            failures.push((
                name.to_string(),
                "doc lacks example block AND math formula".into(),
            ));
        }
    }
    failures
}

#[test]
fn acceptance_ac9() {
    // CARGO_MANIFEST_DIR is set by cargo at compile-time for tests.
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    let src_files = [
        "src/lib.rs",
        "src/linear.rs",
        "src/activation.rs",
        "src/lstm.rs",
        "src/classify.rs",
    ];

    let mut total_pub = 0usize;
    let mut all_failures: Vec<(String, String, String)> = Vec::new();

    for relpath in &src_files {
        let mut p = PathBuf::from(manifest_dir);
        p.push(relpath);
        let contents = match fs::read_to_string(&p) {
            Ok(s) => s,
            Err(e) => {
                all_failures.push((
                    (*relpath).to_string(),
                    "<file>".into(),
                    format!("failed to read: {e}"),
                ));
                continue;
            }
        };
        // Count pub fns for context.
        let pub_count = contents
            .lines()
            .filter(|l| {
                let t = l.trim_start();
                (t.starts_with("pub fn ") || t.starts_with("pub fn\t"))
                    && !l.starts_with(' ')
                    && !l.starts_with('\t')
            })
            .count();
        total_pub += pub_count;
        let fails = check_pub_items(&contents);
        for (n, r) in fails {
            all_failures.push(((*relpath).to_string(), n, r));
        }
    }

    assert!(
        total_pub > 0,
        "AC9: scan found 0 public items — looks like the test is broken, not the docs"
    );
    assert!(
        all_failures.is_empty(),
        "AC9: {} undocumented or under-documented public items: {:?}",
        all_failures.len(),
        all_failures
    );
}
